version: '3.6'
services:
  frontend:
    image: marco79423/mysite-frontend:latest
    depends_on:
      - backend
  backend:
    image: marco79423/mysite-backend:latest
    volumes:
      - "backend-static:/app/static"
      - "backend-media:/app/media"

  # proxy
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - "/etc/letsencrypt/live/marco79423.net/fullchain.pem:/fullchain.pem:ro"
      - "/etc/letsencrypt/live/marco79423.net/privkey.pem:/privkey.pem:ro"

      - "./proxy/proxy.nginx:/etc/nginx/conf.d/default.conf:ro"
      - "./proxy/static:/static:ro"

      - "backend-static:/backend-static"
      - "backend-media:/backend-media"

  # monitor
  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer-data:/data"
volumes:
  backend-static:
  backend-media:

  portainer-data:
