name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  VERSION: $(date +"%y%m%d%H%M%S")

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 設定環境
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 建置和推送 Backend image
      - name: Build backend image
        run: |
          docker build \
            --file backend/Dockerfile \
            --build-arg STATIC_URL=/backend/static/ \
            --build-arg REPO_VERSION=${{env.VERSION}} \
            --tag marco79423/mysite-backend:latest \
            .
      - name: Push backend image
        run: |
          echo "::env VERSION=${{env.VERSION}}"

          docker push marco79423/mysite-backend:latest

          docker tag marco79423/mysite-backend:latest marco79423/mysite-backend:${{env.VERSION}}
          docker push marco79423/mysite-backend:${{env.VERSION}}

      # 建置和推送 Frontend image
      - name: Build frontend image
        run: |
          docker build \
          --file frontend/Dockerfile \
          --build-arg REACT_APP_BACKEND_SERVER_URL=/backend \
          --tag marco79423/mysite-frontend:latest \
          .
      - name: Push frontend image
        run: |
          echo "::env VERSION=${{env.VERSION}}"

          docker push marco79423/mysite-frontend:latest

          docker tag marco79423/mysite-frontend:latest marco79423/mysite-frontend:${{env.VERSION}}
          docker push marco79423/mysite-frontend:${{env.VERSION}}
